require(pbapply)
require(dplyr)
require(readr)
require(raster)
require(purrr)
require(sf)
require(raster)
require(pbapply)
require(bit64)
require(zoo)
require(ggnewscale)
require(lubridate)
require(gbm)
require(rnoaa)
require(e1071)
require(standardize)
require(Metrics)
require(stringr)
require(stats)
require(future)
require(rmarkdown)
require(countrycode)
require(magrittr)
require(ggthemes)
require(scales)
require(tibble)
require(worldmet)
require(sirad)
require(pbmcapply)
require(parallel)
require(cowplot)
require(ggpubr)
require(ranger)
require(Metrics)
require(caTools)
require(deweather)
require(dotenv)
require(e1071)

devtools::install_github("https://github.com/energyandcleanair/rcrea", force=T)
require(rcrea)

devtools::install_github('https://github.com/hubert-thieriot/rmweather', force=T)
require(rmweather)


lapply(list.files('R','*.R',full.names = T), source)
